<?php require './app/templates/header.phtml' ?>

<?php if ($this->session) : require $form; endif ?>

<h4 class="ps-2 fw-bold">Canciones:</h4>
<table class="table">
    <thead>
        <tr>
            <th>Canción</th>
            <th>Artist</th>
            <th>Duración</th>
            <th>Genero</th>
            <?php if ($this->session) : ?>
                <th>Acciones:</th>
            <?php endif ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($songs as $item) : ?>
            <tr>
                <th><a href="songs/<?= $item->id?>"><?= $item->title ?></a></th>
                <td><?= $item->artist ?></a></td>
                <td><?= $item->duration ?></td>
                <td><?= $item->genre_name ?></td>
                <?php if ($this->session) : ?>
                <td>
                    <a href="songs-edit/<?= $item->id ?>" type="button" class='btn btn-warning ml-auto'>Editar</a>
                    <a href="songs-remove/<?= $item->id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                </td>
            </tr>
            <?php endif ?>
            <?php endforeach ?>
        </tbody>
</table>

<?php require './app/templates/footer.phtml' ?>
<script>
        // Asegurarse de que el audio esté completamente cargado
        var rugido = document.getElementById("rugido-dragon");

        // Event listener que avisa cuando el audio está listo
        rugido.addEventListener("canplaythrough", function() {
        console.log("El audio está listo para reproducirse.");
        });

    function reproducirRugido() {
        var rugido = document.getElementById("rugido-dragon");

        // Verificar si el archivo de audio está listo
        if (rugido.readyState >= 2) {
            rugido.play().catch(function(error) {
                console.log("Error al reproducir el audio: ", error);
            });
        } else {
            console.log("El audio no está listo para ser reproducido.");
        }
    }
</script>