<?php require './app/templates/header.phtml' ?>

<?php if ( AuthHelper::check() ) : ?><h4>La sesión ya fué iniciada <a href="genres" class="link-secondary link-underline link-underline-opacity-0">(volver)</a></h4>
<?php else : ?>
<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="auth">
        <div class="form-group">
            <div>
                <img src="..\web2-tpe-master\img\login.jpg" class="imagen-p2">
            </div>
            <label for="user">Usuario</label>
            <input type="text" required class="form-control" id="user" name="user">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" required class="form-control" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>
       
        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
</div>
<?php endif ?>

<?php require './app/templates/footer.phtml' ?>
<script>
        // Asegurarse de que el audio esté completamente cargado
        var rugido = document.getElementById("rugido-dragon");

        // Event listener que avisa cuando el audio está listo
        rugido.addEventListener("canplaythrough", function() {
        console.log("El audio está listo para reproducirse.");
        });

    function reproducirRugido() {
        var rugido = document.getElementById("rugido-dragon");

        // Verificar si el archivo de audio está listo
        if (rugido.readyState >= 2) {
            rugido.play().catch(function(error) {
                console.log("Error al reproducir el audio: ", error);
            });
        } else {
            console.log("El audio no está listo para ser reproducido.");
        }
    }
</script>

